### ISSUE TITLE
Beta UI Q2 2024

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-ui#161]
## April 2024
- [x] #162 
- [x] #177  
- [x] REKT API update
- [x] About tooltip: stability-api `about` string #168 
- [x] #170 
- [x] #173 
- [x] #174 
- [x] #160 
- [x] #167 
- [x] #172 #171 

## May 2024
- [x] #184
- [x] #185
- [x] #186
- [x] Vault: Add to metamask
- [x] #188 
- [x] #169 
- [x] #191 

## June 2024
- [x] #193
- [x] #194  
- [x] #195 
- [x] #198
