### ISSUE TITLE
📆 Beta UI Q3 2024

### ISSUE THREAD

**Issue by DevTeaLeaf** [stabilitydao/stability-ui#200]
## July 2024

- Vault
  - [x] #198 
  - [x] #199 
  - [x] Improve vaults table layout
- Tests
  - [x] #201 
  - [x] test zap + 1inch #206  
- [x] eslint #205 
- [x] fix input amounts
- [x] Navigation update

## Aug 2024
- [x] cover important logic by e2e tests
- [x] #208 
- [x] Form updates & fixes
  - #210 
  - #211 
  - #212

## Sep 2024
- [x] #166
- [x] #214 
- [x] #215
- [x] #216  
- [x] #217 
- [x] #220 
- [x] #221 
- [x] #222 
- [x] #223 
- [x] #225 
- [x] #226 
- [x] #227 
- [x] #228 
- [x] #229 
- [x] fix types errors #230
- [x] fix slow e2e test
- [x] #231 
- [x] #233 
- [ ] #219 
- [x] fix wrong vs hodl apr (sync prices)
