### ISSUE TITLE
📆 Beta UI Q4 2024

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-ui#239]
### Recap

* Design system integrated
* Platform portal implemented
* Users leaderboard
* Yield Contests
* Vault overview upgrade on vault page
* many bugfixes and minor improvements

### Tasks

- [x] #242 
- [x] #243 
- [x] #232 #241 
- [x] #234 
- [x] #235
- [x] #242 #243
- [x] #244 
- [x] #245 
- [x] #246 #247 
- [x] #249 #250 
- [x] #248  
- [x] #236 
- [x] #255
- [x] #258
- [x] #237
- [x] #238 
- [x] setup eslint
- [x] #132
- [x] #36 
- [x] #272 
- [x] #273 
- [x] Bug while processing empty contest leaderboard
- [x] #276
- [x] #277
- [x] #278
- [x] #280 

# November

- [x] #286 
- [x] #287
- [x] #297
- [x] #291
- [x] #292
- [x] #293
- [x] #288
- [x] #285
- [x] #282
- [x] #294
- [x] Platform -> Assets -> Asset
- [x] #312

# December

- [ ] #318
- [ ] #269
- [ ] #296
- [x] #284
- [ ] #127
- [x] #189 
- [ ] #270 
- [x] #304
- [x] #313
- [x] #314
- [x] #316
- [ ] platform static pages and routing for SEO and performance
- [ ] [BLOCKED] Vaults -> Vault -> InvestForm -> Settings: manage 1inch protocols
- [ ] #268 
- [ ] #240 
- [x] #325
