### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-ui#4]
## Vault page

* [x] #1 
* [x] #16 
* [x] #18  assets logo, symbol, name, network
* [x] #20  Your deposit, TVL, APY, Daily, Last HardWork
* [x] #30 share price, vault type
* #21 
  * [x] name, specific, strategy address, vault address, gh link
  * [x] APY breakdown (from vaults apy tooltip)
  * [x] description
  * [x] base strategy names
  * [x] AMM adapter (for `ILPStrategy` ERC165)
* Investing component
  * [x] #15 
  * [x] #22 
  * asset0+asset1
    * [x] approve
    * [x] preview deposit
    * [x] #17 
    * [x] withdraw
    * [x] #25 
  * ZAP blue-chip
    * [x] coming soon
  * underlying
    * [x] approve
    * [x] #33 
    * [x] withdraw
    * [x] preview withdraw
* Design
  * [x] select image
* Assets
  * [x] logo, name, symbol, price, address
  * [x] #24 
    * [x] description
    * [x] website
    * [x] docs
    * [x] tags: stablecoin, bridged
