### ISSUE TITLE
Beta UI Q1 2024

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-ui#7]
## January 2024
- [x] footer with social buttons
- [x] #63 
- [x] #62 
- [x] #57 
- [x] #59 
- [x] #58 
- [x] #72 
- [x] #90 
- [x] #78
- [x] #77
- [x] #87 
- [x] platform name, version, tvl in end of Portfolio block
- [x] fix api data loading bug

## February 2024
- [x] #108
- [x] #100 
- [x] #114
- [x] #115
- [x] #104 
- [x] Vault - Strategy: Rebalances 24h, Rebalances 7days
- [x] loader insted Loading vaults..
- [x] Vault - Invest form - Underlying
  - remove Swaps block
  - show you receuve amount on withdraw
- [x] Vaults: styling #126 
- Loading
  - [x] Vaults: show list when subgraph ready
  - [x] retry subgraph api (2 times)
  - [x] show error and Reload button on loading error below loader
- [x] provider logo
- [x] #141 #138 #137 #140 #139 
- [x] #86 #124 
- [x] Vault -> Strategy: APR table #142 #143 
  - columns: Latest, 24h, Week
  - lines: Total APY, Total APR, Pool swap fees APR, Strategy APR/Farm APR

## March 2024
* **Vaults**
  - [x] #145 
  - [x] #146
  - [x] #147
  - [x] #149 
  - [x] #150 
  - [x] #155 
  - [x] #158 
  - [x] APR switcher: latest / 24h / weekly #144 
  - [x] About tooltip: Smart Contracts: Stability Platform xx.xx-alpha
  - [x] About tooltip: User Interface: stability-ui <version> <build date>
* **Vault page**
  - [x] #154 
  - [x] #103
  - [x] #80 
  - [x] Vault layout
  - [x] #148
  - [x] #151 
  - [x] #152 
  - [x] #153 
  - [x] ZAP withdraw error
  - [x] Assets: price at creation
  - [x] Assets: invested (amount / %)
  - [x] #156
  - [x] #157
  - [x] #159
